GET http://localhost:8000/employees

###

POST http://localhost:8000/employees
Content-Type: application/json

{
    "firstName" : "Dineshwar",
    "lastName" : "s"
}
###

PUT http://localhost:8000/employees
Content-Type: application/json

{
    "id" : 2,
    "firstName" : "Dineshwar",
    "lastName" : "sddd"
}

###

DELETE http://localhost:8000/employees
Content-Type: application/json

{
    "id" : 2
}
###

GET http://localhost:8000/employees/1
